### PR TITLE
Added the details to the major characteristics table to show support of known front framework

### PR DESCRIPTION
**Pull request by gpsakthivel**
- Issue no: 301
- Added the details to the major characteristics table to show support of known front framework
  -  Angular
  - React
  - Nextjs
  - Vue
  - Nuxt
  - Svelte
  - Vite

### CODE REVIEW

**Comment by Elanis** [comment]
Hello !

I'm sorry but I think I explained incorrectly that I wanted a table containing the support of each front-end framework for the technologies already listed in the benchmarks.

I was thinking of a new table using the same layout as Operating Systems support:

E.g:
| | [Electron](https://github.com/electron/electron) | [NW.JS](https://github.com/nwjs/nw.js) | [Tauri](https://github.com/tauri-apps/tauri) | [Flutter](https://github.com/flutter/flutter) |
|---------|----------|--------|--------|---------|
| Angular | Yes/No   | Yes/No | Yes/No | Yes/No  |
| React  | Yes/No   | Yes/No | Yes/No | Yes/No  |
| VueJS | Yes/No   | Yes/No | Yes/No | Yes/No  |
| Vite | Yes/No | Yes/No | [Yes, official support](https://tauri.app/fr/v1/guides/getting-started/setup/vite/) | Yes/No |

Also, since the readme is autogenerated from https://github.com/Elanis/web-to-desktop-framework-comparison/blob/main/runner/README.template.begin.md and https://github.com/Elanis/web-to-desktop-framework-comparison/blob/main/runner/README.template.end.md, you should edit those files and run `node writer.js` (in runner/ directory) to regenerate the README.md file :)

**Comment by gpsakthivel** [comment]
Hmm. My bad. I should have asked much more requirement details before starting the issue. Will look into it later if your okay with that.

**Comment by Elanis** [comment]
No problem, it's okay :)

Also, fyi, today I updated figures for the readme file (I update deps every first week of the month), so you will be one commit late on your fork :)

**Comment by Elanis** [comment]
https://github.com/Elanis/web-to-desktop-framework-comparison/commit/747cebc0830d4f464380d524fd3102502f7eccdd replaces this PR

**Pull request closed without merging**
